version: '3.8'
services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ebiz
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrantdata:/qdrant/storage
    restart: unless-stopped

volumes:
  pgdata:
  qdrantdata: 