version: '3.8'
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ebizadmin
      POSTGRES_PASSWORD: ebiz_secure_pwd
      POSTGRES_DB: ebiz_saas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ebizadmin -d ebiz_saas"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin Web Interface
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ebiz.com
      PGADMIN_DEFAULT_PASSWORD: admin_secure_pwd
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  # Qdrant Vector Database (for AI features)
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT_ALLOW_RECOVERY_MODE: "true"

volumes:
  postgres_data:
  pgadmin_data:
  qdrant_data: 