services:
  # PostgreSQL Database - configured to match Prisma connection string
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ebizadmin
      POSTGRES_PASSWORD: ebiz_secure_pwd
      POSTGRES_DB: ebiz_saas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ebizadmin -d ebiz_saas"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: 